---
- name: Configure student vpn to headend
  hosts: mysrx
  connection: local
  gather_facts: no
  vars:
    junos_user: "root"
    junos_password: "Juniper"
    build_dir: "/tmp/"
    mss_entries: [ {'protocol': 'ipsec-vpn', 'mss': '1350'} ]
    interfaces: [
      {'interface': 'st0', 'unit': '{{pod_id}}', 'family': 'inet', 'addr_type': 'address', 'addr': '10.255.{{pod_id}}.2/30', 'zone':'vpn', 'hit_protocols': ['ospf', 'bgp'], 'hit_services': ['ping', 'traceroute']},
      {'interface': 'ge-0/0/2', 'unit': '0', 'family': 'inet', 'addr_type': 'dhcp', 'zone':'untrust', 'hit_services': ['ike','ping','ssh','netconf']}
    ]
    ike: [ {'ike_name': 'ike-vpn', 'gateway_ip': '10.10.0.5', 'ext_interface': 'ge-0/0/2.0', 'ike_policy_name': 'ike-policy1', 'ike_policy_mode': 'main', 'ike_policy_proposal': 'standard', 'shared_secret': 'AwesomePassword123'} ]
    ipsec: [ {'ipsec_policy_name': 'vpn-policy1', 'ipsec_policy_mode': 'standard', 'ipsec_vpn_name': 'ipsec-vpn', 'ike_gateway': 'ike-vpn', 'tunnel_int': 'st0.1'} ]


  tasks:
    - name: set flow tcp-mss
      template: src=templates/sec_flow_tcp_mss.set.j2 dest={{build_dir}}/sec_flow_tcp_mss.set
      with_items: mss_entries

    - name: Apply flow tcp-mss
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/sec_flow_tcp_mss.set overwrite=no logfile=logs/{{ inventory_hostname }}.log

    - name: Build vpn tunnel interface
      template: src=templates/interfaces.set.j2 dest={{build_dir}}/interfaces.set
      with_items: interfaces

    - name: Apply vpn tunnel interface
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/interfaces.set overwrite=no logfile=logs/{{ inventory_hostname }}.log

    - name: Build vpn zone
      template: src=templates/interfaces_zone.set.j2 dest={{build_dir}}/interfaces_zone.set
      with_items: interfaces

    - name: Apply vpn zone
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/interfaces_zone.set overwrite=no logfile=logs/{{ inventory_hostname }}.log

    - name: Build VPN Phase 1
      template: src=templates/vpn_ike.set.j2 dest={{build_dir}}/vpn_ike.set
      with_items: ike

    - name: Apply VPN Phase 1
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/vpn_ike.set overwrite=no logfile=logs/{{ inventory_hostname }}.log

    - name: Build VPN Phase 2
      template: src=templates/vpn_ipsec.set.j2 dest={{build_dir}}/vpn_ipsec.set
      with_items: ipsec

    - name: Apply VPN Phase 2
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/vpn_ipsec.set overwrite=no logfile=logs/{{ inventory_hostname }}.log
